# Generated by Django 4.1.7 on 2023-03-09 18:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("buyingfrenzy", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="openhours",
            name="day",
            field=models.CharField(max_length=6),
        ),
    ]
