# Generated by Django 4.1.7 on 2023-03-08 06:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("buyingfrenzy", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="menu",
            old_name="restaurant",
            new_name="restaurant_name",
        ),
    ]
